### ISSUE TITLE
Missing dependency: kramdown

### ISSUE THREAD

**Issue by emj365** [aymerick/jekyll-example#2]
```
$ grunt -v
Initializing
Command-line options: --stack, --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bower-task" local Npm module tasks.
Reading /Users/michaeljin/git/jekyll-example/node_modules/grunt-bower-task/package.json...OK
Parsing /Users/michaeljin/git/jekyll-example/node_modules/grunt-bower-task/package.json...OK
Loading "bower_task.js" tasks...OK
+ bower

Registering "grunt-contrib-connect" local Npm module tasks.
Reading /Users/michaeljin/git/jekyll-example/node_modules/grunt-contrib-connect/package.json...OK
Parsing /Users/michaeljin/git/jekyll-example/node_modules/grunt-contrib-connect/package.json...OK
Loading "connect.js" tasks...OK
+ connect

Registering "grunt-contrib-copy" local Npm module tasks.
Reading /Users/michaeljin/git/jekyll-example/node_modules/grunt-contrib-copy/package.json...OK
Parsing /Users/michaeljin/git/jekyll-example/node_modules/grunt-contrib-copy/package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /Users/michaeljin/git/jekyll-example/node_modules/grunt-contrib-watch/package.json...OK
Parsing /Users/michaeljin/git/jekyll-example/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-exec" local Npm module tasks.
Reading /Users/michaeljin/git/jekyll-example/node_modules/grunt-exec/package.json...OK
Parsing /Users/michaeljin/git/jekyll-example/node_modules/grunt-exec/package.json...OK
Loading "exec.js" tasks...OK
+ exec
Initializing config...OK
Loading "Gruntfile.coffee" tasks...OK
+ build, default, serve

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "serve" task

Running "build" task

Running "copy" task

Running "copy:jquery" (copy) task
Verifying property copy.jquery exists in config...OK
Files: bower_components/jquery/dist/jquery.min.js -> vendor/js/jquery.min.js
Options: encoding="utf8", processContent=false, processContentExclude=[], mode=false
Copying bower_components/jquery/dist/jquery.min.js -> vendor/js/jquery.min.js
Reading bower_components/jquery/dist/jquery.min.js...OK
Writing vendor/js/jquery.min.js...OK
Copied 1 files

Running "copy:bootstrap" (copy) task
Verifying property copy.bootstrap exists in config...OK
Files: bower_components/bootstrap/dist/css/bootstrap.min.css -> vendor/css/bootstrap.min.css
Files: bower_components/bootstrap/dist/js/bootstrap.min.js -> vendor/js/bootstrap.min.js
Options: encoding="utf8", processContent=false, processContentExclude=[], mode=false
Copying bower_components/bootstrap/dist/css/bootstrap.min.css -> vendor/css/bootstrap.min.css
Reading bower_components/bootstrap/dist/css/bootstrap.min.css...OK
Writing vendor/css/bootstrap.min.css...OK
Copying bower_components/bootstrap/dist/js/bootstrap.min.js -> vendor/js/bootstrap.min.js
Reading bower_components/bootstrap/dist/js/bootstrap.min.js...OK
Writing vendor/js/bootstrap.min.js...OK
Copied 2 files

Running "exec:jekyll" (exec) task
Verifying property exec.jekyll exists in config...OK
File: [no files]

jekyll build --trace
Expecting exit code 0
>> WARN: Unresolved specs during Gem::Specification.reset:
>>       listen (~> 3.0)
>> WARN: Clearing out unresolved specs.
>> Please report a bug if this causes problems.
Configuration file: /Users/michaeljin/git/jekyll-example/_config.yml
            Source: /Users/michaeljin/git/jekyll-example
       Destination: /Users/michaeljin/git/jekyll-example/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
>> You are missing a library required for Markdown. Please run:
>>   $ [sudo] gem install kramdown
>>   Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2014-07-22-welcome-to-jekyll.markdown':
>>                     Missing dependency: kramdown
>>              ERROR: YOUR SITE COULD NOT BE BUILT:
>>                     ------------------------------------
>>                     Missing dependency: kramdown
>> Exited with code: 1.
Warning: Task "exec:jekyll" failed. Use --force to continue.
Error: Task "exec:jekyll" failed.
    at Task.<anonymous> (/Users/michaeljin/git/jekyll-example/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (/Users/michaeljin/git/jekyll-example/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout (timers.js:89:15)

Aborted due to warnings.
```

**Comment by emj365** [comment]
References: http://stackoverflow.com/a/32233986/811653
